# Exported from Render on 2026-02-12T07:10:32Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: terabox
      runtime: python
      repo: https://github.com/uk306927-ui/terabox
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: python teraaaaa1.py
      autoDeployTrigger: commit
